### ISSUE TITLE
How can I obtain the exit code?

### ISSUE THREAD

**Issue by mfiano** [ruricolist/cmd#19]
I would like to programmatically obtain the exit code of a `uiop/run-program:subprocess-error` condition being signalled. I'm not too familiar with UIOP's inner workings here, or if `cmd` has a means to obtain that, but I think it's important for being able to resignal contextual error conditions, or handle them gracefully, given the documented error codes of a particular process being invoked.

**Comment by mfiano** [comment]
In reading the code a bit more, I see that what I want is a hybrid of `$cmd` and `cmd?`, that is something that returns a string and an exit status as its second return value.

**Comment by mfiano** [comment]
After a bit of trial and error, I came up with a rather hacky solution that could surely be implemented a bit better:

```lisp
(defun cmd% (cmd &rest args)
  (let* ((exit-code 0)
         (result (serapeum:chomp
                  (with-output-to-string (out)
                    (setf exit-code (apply #'cmd:cmd cmd
                                           :error-output nil
                                           :output out
                                           :ignore-error-status t
                                           args))))))
    (if (zerop exit-code)
        (values result exit-code)
        (values nil exit-code))))
```

**Comment by ruricolist** [comment]
I'm not clear on what the question is here. Do you want to get the exit code from the error (e.g. using `uiop:subprocess-exit-code` on the condition)  or do you want the error status to be returned in the general case, even when using `:ignore-error-status t`?

**Comment by mfiano** [comment]
I would like the error status to be returned with the stringifying `$cmd` case.

Edit: But maybe using `uiop:subprocess-error-code` on the condition is more sane. I don't expect you to change the semantics or combinitorially add new cmd variants.

**Comment by ruricolist** [comment]
I've added a second value to `$cmd`. `cmd?` already returns the exit code as a second value, so it makes sense in terms of consistency.
