### ISSUE TITLE
Mishandling of pathname arguments with spaces

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/cmd#21]
```lisp
> (uiop:directory-exists-p #p"foo bar")
#P"/home/ambrevar/foo bar/"
> (cmd:cmd "ls" #p"foo bar")
ls: cannot access 'foo': No such file or directory
ls: cannot access 'bar': No such file or directory
```

I'm guessing there is a bug and the pathname native-namestring is tokenized instead of being passed as-is.

**Comment by ruricolist** [comment]
This is a serious bug but I can't reproduce it. Can you verify it happens with the latest master?

**Comment by ruricolist** [comment]
Never mind, I found the problem -- it only happens when the compiler macro for cmd doesn't trigger.

**Comment by Ambrevar** [comment]
Fixed indeed, thanks a lot!
