### ISSUE TITLE
Add an (opt-in) readtable for convenience?

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/cmd#3]
The Clesh library (https://github.com/Neronus/Clesh) is very convenient.  When it comes to executing shell from a Lisp REPL, it's as short as it comes:

```
> !ls -l
total 48
-rw-r--r-- 1 ambrevar users 35147 Nov 30 09:29 COPYING
-rwxr-xr-x 1 ambrevar users  6660 Jan 12 13:43 lisp-repl-core-dumper
-rw-r--r-- 1 ambrevar users  3566 Jan 12 13:44 readme.org
```

Unfortunately, the project is not actively maintained (https://github.com/Neronus/clesh/issues/7#issuecomment-506021158), plus the implementation has a few shortcomings (https://github.com/Neronus/clesh/issues/7#issuecomment-724709420).
Finally, it does not allow for the fine-grained control of `cmd`.

So what about borrowing `clesh` idea for `cmd` and add a named-readtable like, roughly, the following:

- `!`: pass the rest of the line to `cmd`.
- `&`: pass the rest of the line to `cmd&`.
- `$`: pass the rest of the line to `$cmd`.

Example:

```lisp
> !ls -l
; as above
> $ls -l
"total 48
-rw-r--r-- 1 ambrevar users 35147 Nov 30 09:29 COPYING
-rwxr-xr-x 1 ambrevar users  6660 Jan 12 13:43 lisp-repl-core-dumper
-rw-r--r-- 1 ambrevar users  3566 Jan 12 13:44 readme.org"
```

Thoughts?

**Comment by ruricolist** [comment]
I like the idea as long as it's defined in a separate system (like `cmd/readtable`).

**Comment by Ambrevar** [comment]
OK, I'll work on it and send a patch.

**Comment by Ambrevar** [comment]
See #11.
