### ISSUE TITLE
defvar all the external executables

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/cmd#8]
I tried running `cmd` in a Guix container and it failed, complaining that `env` was missing.
This is because coreutils were not in the container.

To avoid this, the Guix package (or Nix package for that matters) should explicitly reference the coreutils binaries.  It's easy to do this if the `cmd` code `defvar`s (or equivalent) all the external executable in a clearly visible spot.

Example

```lisp
(defvar env-command "env")
; etc.
```

which then can easily be patched by package maintainers to

```lisp
(defvar env-command "/guix/store/...-coreutils/bin/env")
; etc.
```

Thanks in advance! :)

**Comment by ruricolist** [comment]
Would kill, ps, and tr also need defvars, or just env?

**Comment by Ambrevar** [comment]
Yes, all of them :)

**Comment by Ambrevar** [comment]
Perfect, thanks!
