### ISSUE TITLE
Add shell command wrapper

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/cmd#9]
`cmd` wraps around most features of `uiop:launch-program`, except for running a command in a shell (like `uiop:launch-program` would do if the first argument is a string).

Of course one can write `(cmd "bash -c '...'")` but this is tedious.

What about adding `sh`, `sh&`, `$sh`, etc. which would do just like their `cmd` counterparts, except they would pass their argument to a shell just like `uiop:launch-program`?

Example implementation:

```lisp
(export-always '*shell*)
(defvar *shell* "sh"
  "Default shell to use in `sh' and friends.
Also see `*shell-command-flags*'.")

(export-always '*shell-command-flag*)
(defvar *shell-command-flag* "-c"
  "Flag to pass a command string to the `*shell*'.")

(defun format-shell-command (shell-command)
  (format nil "~a ~a '~a'"
          *shell* *shell-command-flag* shell-command))

(export-always 'sh)
(defun sh (shell-command)
  "Wrapper around `cmd:cmd' to execute SHELL-COMMAND in `*shell*'."
  (cmd:cmd (format-shell-command shell-command)))

(export-always 'sh&)
(defun sh& (shell-command)
  "Wrapper around `cmd:cmd&' to execute SHELL-COMMAND in `*shell*'."
  (cmd:cmd& (format-shell-command shell-command)))

(export-always '$sh)
(defun $sh (shell-command)
  "Wrapper around `cmd:$cmd' to execute SHELL-COMMAND in `*shell*'."
  (cmd:$cmd (format-shell-command shell-command)))
```

**Comment by ruricolist** [comment]
This is a feature I would rather not include. The idea of cmd is to avoid having to use a shell, and all the dangers of accidental (or malicious!) shell interpolation. And users can always use `run-program` or `launch-program` directly; cmd isn't adding any value here.

**Comment by Ambrevar** [comment]
I understand.  On the other hand, you could argue the same about `cmd`: the user could always use `run-program` :)  (I know, `cmd` does more than that... :p)

What `sh` and friends add here is conciseness and shorthands to specify which kind of outputs (or input) the user wants.

The consistency with `cmd` is nice and they mix well together.

The dangers of the shell are the responsibility of the user: should they use `sh` or `run-program`, the danger is just the same.

Finally, if we consider this in the bigger picture of #11, then this library is all we need to use SLIME / SLY as a full-blown shell :)

**Comment by Ambrevar** [comment]
Neat, thanks a lot!
